spring.application.name=pertemuan11

# Menggunakan port 5432 dan kredensial docker yang sudah diperbarui
spring.datasource.url=jdbc:postgresql://localhost:30000/praktikum_db
spring.datasource.username=praktikum_user
spring.datasource.password=12345

#spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect